<a href="https://colab.research.google.com/github/nelsononeoc/manipulacion_de_datos_Pandas/blob/main/manipulaci%C3%B3n_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
datos=pd.read_json("datos_hosting.json")

In [3]:
datos.head()

                                      info_inmuebles
0  {'evaluacion_general': '10.0', 'experiencia_lo...
1  {'evaluacion_general': '10.0', 'experiencia_lo...
2  {'evaluacion_general': '10.0', 'experiencia_lo...
3  {'evaluacion_general': '10.0', 'experiencia_lo...
4  {'evaluacion_general': '10.0', 'experiencia_lo...

In [4]:
datosdf = pd.json_normalize(datos['info_inmuebles'])

In [5]:
datosdf.head(10)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
5,10.0,--,16,"[Stunning Designsponge featured 6 bed, 3.75 ba...",[Queen Anne is THE BEST and most desirable nei...,"[3, 4, 3]","[6, 7, 4]","[15, 10, 10]","[Real Bed, Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$1,500.00, $1,500.00, $250.00]","[$300.00, $300.00, $100.00]","[$461.00, $375.00, $250.00]"
6,10.0,--,2,[We're renting out a small private unit of one...,[This part of Queen Anne has wonderful views a...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Wireless Internet"",""Free Parking on Premise...","[$0, $150.00, $150.00, $0, $0, $100.00, $0, $0...","[$40.00, $0, $25.00, $0, $15.00, $15.00, $20.0...","[$120.00, $80.00, $60.00, $90.00, $95.00, $99...."
7,10.0,--,3,"[Why stay in a hotel costing more, when you ca...",[West Queen Anne is on the bluff overlooking P...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, ...","[2, 2, 1, 2, 1, 1, 1, 2, 3, 1, 1, 2, 2, 2, 1, ...","[Real Bed, Real Bed, Futon, Real Bed, Real Bed...","[{TV,Internet,""Wireless Internet"",Kitchen,""Ind...","[$0, $0, $0, $100.00, $0, $0, $0, $200.00, $0,...","[$100.00, $50.00, $20.00, $45.00, $50.00, $0, ...","[$148.00, $150.00, $137.00, $97.00, $200.00, $..."
8,10.0,--,4,[Make your self at home in this charming one-b...,"[--, Queen Anne is a wonderful, truly function...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, ...","[1, 1, 3, 1, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$0, $100.00, $300.00, $0, $0, $0, $100.00, $0...","[$0, $40.00, $95.00, $40.00, $50.00, $50.00, $...","[$85.00, $150.00, $245.00, $175.00, $125.00, $..."
9,10.0,--,5,"[Enjoy our amazing, updated & modern design co...",[Queen Anne hill became a popular spot for the...,"[1, 2, 1, 1, 2, 3, 1, 1, 2, 1, 2, 1, 1, 1, 3, ...","[2, 3, 1, 2, 2, 3, 1, 1, 3, 3, 3, 1, 3, 2, 3, ...","[3, 3, 1, 4, 2, 5, 3, 4, 3, 3, 3, 2, 3, 3, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$400.00, $500.00, $0, $250.00, $100.00, $0, $...","[$85.00, $150.00, $0, $75.00, $50.00, $150.00,...","[$165.00, $600.00, $150.00, $129.00, $135.00, ..."

In [6]:
columnas = list(datosdf.columns)
columnas

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_baños',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

In [7]:
datos=datosdf.explode(columnas[3:])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [8]:
datos.reset_index(inplace=True,drop=True)
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

en este metodo es importante tener el True con la primera letra en mayuscula por que osino el programa no lo reconoce
en este caso se uso el metodo .reset_index para resetear el indice del dataset por que como expandimos las listas que venian en el JSON originalmente eran un solo registro pero en unas columna en este caso desde la tercera columna estaban anidados por eso al separarlo y por buenas practica es necesario que cada registro tenga un indice unico

In [9]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

cuando el contenido de la columna no es identificado se coloca de tipo object por o tambien cuando la info es de tipo texto esto lo realiza de manera automatica Python acontinuacion se van a trabajar para asignarle el tipo correcto a cada dato

In [10]:
import numpy as np

In [11]:
datos['max_hospedes']= datos['max_hospedes'].astype(np.int64)

en esta parte se selecciona la columna datos['max_hospedes'] y se le aplica lla funcion de la libreria numpy para asignar valores en este caso se especifica que se va a trabajar con datos de tipo entero si en algun valor de la columna no es entero esto no va a funcionar

In [12]:
columnas_numericas = ['cantidad_baños','cantidad_cuartos', 'cantidad_camas']

In [13]:
datos[columnas_numericas]= datos[columnas_numericas].astype(np.int64)

In [14]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [15]:
datos['evaluacion_general']= datos['evaluacion_general'].astype(np.float64)

In [16]:
datos['precio']=datos['precio'].apply(lambda x: x.replace('$','').replace(',','').strip())

en este caso como la columna precio tenia un caracter de signo pesos es necesario hacerle una tranformacion para pposterior asignar un tipo de dato corecto para esto se utilizo la funcion lamda que lo que hace es recorrer toda la columna y aplicrale un funcion que definimos mas adelante en este caso la llamamos "X" que es el remplazar ese simbolo con nada y en el  ejemplono solo hicimos una tranformacion se realizaron tres tranformacionos la primera quita el signo pesos de los registros que encuentre en la segunda decimos si encuentra una , retirela (python reconoce y trabaja bien con los valores flotantes separados por . no por , por eso esa transformacion y por ultimo se aplica .strip que lo que hace es eliminar los espacios ya sea al inicio o al final)

In [17]:
datos['precio']= datos['precio'].astype(np.float64)

In [18]:
datos[['cuota_deposito','cuota_limpieza']] = datos[['cuota_deposito','cuota_limpieza']].map(lambda x: x.replace('$','').replace(',','').strip())

cuando es una unica columna tenemos una serie si tenemos mas de una columna ya python lo trata como un dataframe por eso es necesario cambiar como se se aplica las tranformaciones que estan diseñadas solo para aplicar sobre series por eso el applymap

In [19]:
datos[['cuota_deposito','cuota_limpieza']]=datos[['cuota_deposito','cuota_limpieza']].astype(np.float64)

# datos de texto
vamos a tokenizar cada palabra va a ser un token

In [20]:
datos['descripcion_local']=datos['descripcion_local'].str.lower() #se tramforma los valores en tipo texto y se les aplica la funcion lower que devuelve el texto en minuscula

In [21]:
datos['descripcion_local']=datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)#en esta parte le estoy pidiendo que me replace todo menso [^a-zA-Z0-9\-\'] esa negacion se logra con el ^

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipython-input-417222874.py:1: SyntaxWarning: invalid escape sequence '\-'
  datos['descripcion_local']=datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)#en esta parte le estoy pidiendo que me replace todo menso [^a-zA-Z0-9\-\'] esa negacion se logra con el ^

In [22]:
datos['descripcion_local']= datos['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-1682908067.py:1: SyntaxWarning: invalid escape sequence '\w'
  datos['descripcion_local']= datos['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [23]:
datos['descripcion_local'].head(10)

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one  convenientl...
4    the  studio at mibbett hollow' is in a beautif...
5    built  run and supported by seattle tech and s...
6    built  run and supported by seattle tech and s...
7    built  run and supported by seattle tech and s...
8    built  run and supported by seattle tech and s...
9    built  run and supported by seattle tech and s...
Name: descripcion_local, dtype: object

In [24]:
datos['descripcion_local']= datos['descripcion_local'].str.split()#en este caso el split separa cada palabra y devuelve una lista por defecto el separador es el espacio

In [25]:
datos['comodidades']= datos['comodidades'].str.replace('\{|}]|\"','',regex=True)
#en este caso se pide con el \ que busque algo en especifico y el | me dice es ademas busca este otro signo

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
/tmp/ipython-input-4095802664.py:1: SyntaxWarning: invalid escape sequence '\{'
  datos['comodidades']= datos['comodidades'].str.replace('\{|}]|\"','',regex=True)

In [26]:
datos['comodidades']= datos['comodidades'].str.split(',')
datos['comodidades'].head()

0    [Internet, Wireless Internet, Kitchen, Free Pa...
1    [TV, Internet, Wireless Internet, Kitchen, Fre...
2    [TV, Internet, Wireless Internet, Kitchen, Fre...
3    [Internet, Wireless Internet, Kitchen, Free Pa...
4    [Wireless Internet, Kitchen, Free Parking on P...
Name: comodidades, dtype: object

Datos de tiempo

In [31]:
dt_data= pd.read_json('/content/inmuebles_disponibles.json')
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  object
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [29]:
dt_data.head()

    id       fecha  lugar_disponible precio
0  857  2016-01-04             False   None
1  857  2016-01-05             False   None
2  857  2016-01-06             False   None
3  857  2016-01-07             False   None
4  857  2016-01-08             False   None

In [33]:
dt_data['fecha']= pd.to_datetime(dt_data['fecha'])

In [34]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [35]:
dt_data.groupby(dt_data['fecha'].dt.strftime('%Y-%m'))['lugar_disponible'].sum()

fecha
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: lugar_disponible, dtype: int64